server:
  port: 80

spring:
  application:
    name: gateway
  cloud:
    gateway:
#      开启从注册中心动态创建路由的功能，通过服务名进行路由
      discovery:
        locator:
          enabled: true
      routes:
        - id: consumer
          uri: lb://consumer
          predicates:
            - Path=/proxy/*/consumer/info/**        # 断言，路径前缀为该规则，则放行
#            - Cookie=name,suber             # 断言，cookie 携带name=suber 则放行
#        静态路由，下游服务的ip是固定的。不适用于云原生环境
#      routes:
#        - id: consumer
#          uri: http://localhost:8001
#          predicates:
#            - Path=/consumer/info/**
eureka:
  client:
    #    true表示将自己注册到eureka
    registerWithEureka: true
    #    true表示eureka上抓取注册的服务信息。默认为true.
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/
