server:
  port: 8001

spring:
  application:
    name: consumer
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driverClassName: org.gjt.mm.mysql.Driver
#    url: jdbc:mysql://192.168.10.10:13306/provider?useUnicode=true&characterEncoding=utf-8&useSSL=false
#    username: root
#    password: Abcd1234..

eureka:
  client:
#    true表示将自己注册到eureka
    registerWithEureka: true
#    true表示eureka上抓取注册的服务信息。默认为true.
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/


mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.suber.provider.entities

ribbon:
#  指的是建立连接后从服务器读取到的可用资源所用的时间
  ConnectTimeout: 1000
#  指的是建立链接所用的时间，使用与网络状态正常的情况下，两端连接所用的时间
  ReadTimeout: 10000

logging:
  level:
#    feign以什么日志级别，监控那个接口
    com.suber.consumer.client.PaymentFeignClient: debug


config:
  name: jack
  age: 18