server:
  port: 8002

spring:
  application:
    name: provider
    alias: provider2
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://192.168.10.10:13306/provider?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: Abcd1234..
eureka:
  client:
    #    true表示将自己注册到eureka
    registerWithEureka: true
    #    true表示eureka上抓取注册的服务信息。默认为true.
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instanceId: provider2
    #    ip地址可以显示
    preferIpAddress: true

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.suber.common.entities
